#!/usr/bin/env python3
"""
Catalogue des sujets du blog — 100 articles, une problématique par article.

RÈGLE DE CONSTRUCTION
Chaque entrée part d'une QUESTION que se pose réellement un dirigeant de PME,
pas d'un mot-clé. « Faut-il un data scientist pour démarrer ? » se cherche et se
lit ; « Intelligence artificielle entreprise » ne se lit pas.

Les sujets ne se recouvrent pas : c'est la condition pour que 100 articles
valent mieux que 20. Deux articles qui répondent à la même question se
cannibalisent au référencement.

CHAMPS
  slug      l'URL, définitive — la changer casse les liens entrants
  titre     ce qui s'affiche et se référence
  pole      rattachement éditorial, sert au maillage interne
  question  la problématique traitée, en une phrase
  angle     ce que l'article apporte que les autres n'ont pas
"""

POLES = {
    'audit':        'Audit et diagnostic',
    'automatisation': 'Automatisation et workflows',
    'modeles':      'Modèles et LLM',
    'conduite':     'Conduite du changement',
    'conformite':   'Conformité et sécurité',
    'metiers':      'Par métier',
    'secteurs':     'Par secteur',
    'formation':    'Formation et compétences',
    'pilotage':     'ROI et pilotage',
    'technique':    'Mise en œuvre technique',
}

# Page du site vers laquelle chaque pôle renvoie en priorité.
ANCRAGE = {
    'audit': 'audit-ia.html', 'automatisation': 'automatisation-ia.html',
    'modeles': 'modeles-ia.html', 'conduite': 'consulting-ia.html',
    'conformite': 'agents-ia.html', 'metiers': 'cas-usage.html',
    'secteurs': 'cas-usage.html', 'formation': 'formation-initiation-ia.html',
    'pilotage': 'consulting-ia.html', 'technique': 'integration-ia.html',
}

SUJETS = [
 # ── Audit et diagnostic ───────────────────────────────────────────────────
 ('par-ou-commencer-ia-pme', "Par où commencer l'IA quand on dirige une PME de 20 personnes", 'audit',
  "Un dirigeant sans service informatique ne sait pas quelle est la première action concrète.",
  "Un ordre de départ en quatre semaines, sans achat de licence."),
 ('identifier-taches-automatisables', "Comment repérer les tâches automatisables dans son entreprise", 'audit',
  "On sait que du temps se perd, on ne sait pas où exactement.",
  "Une méthode de relevé sur une semaine, feuille de papier suffisante."),
 ('audit-ia-que-contient-il', "Ce que contient réellement un audit IA, livrable par livrable", 'audit',
  "Le mot audit recouvre tout et n'importe quoi.",
  "La liste des livrables exigibles, pour comparer deux prestataires."),
 ('signes-entreprise-pas-prete-ia', "Sept signes qu'une entreprise n'est pas prête pour l'IA", 'audit',
  "Investir trop tôt coûte plus cher qu'attendre.",
  "Les prérequis réels : données, processus écrits, sponsor."),
 ('cartographie-processus-avant-ia', "Cartographier ses processus avant d'automatiser quoi que ce soit", 'audit',
  "Automatiser un processus mauvais donne un processus mauvais plus rapide.",
  "La différence entre le processus décrit et le processus vécu."),
 ('diagnostic-donnees-entreprise', "Vos données sont-elles exploitables ? Le diagnostic en dix questions", 'audit',
  "Tout le monde dit avoir des données, peu les ont exploitables.",
  "Dix questions à poser, et ce que chaque réponse implique."),
 ('audit-gratuit-piege-ou-pas', "Un audit IA gratuit, c'est un piège commercial ?", 'audit',
  "La gratuité éveille la méfiance, à juste titre.",
  "Ce qu'un audit gratuit peut et ne peut pas couvrir."),
 ('priorisation-cas-usage-ia', "Prioriser ses cas d'usage IA quand on ne peut en faire qu'un", 'audit',
  "Le budget ne permet qu'un chantier la première année.",
  "Une grille effort/impact adaptée aux structures de moins de 50 personnes."),
 ('erreurs-premier-projet-ia', "Les cinq erreurs qui plombent un premier projet IA", 'audit',
  "Le premier projet décide de la suite : réussi, il en ouvre dix.",
  "Chaque erreur avec son signal d'alerte précoce."),
 ('faut-il-data-scientist', "Faut-il recruter un data scientist pour démarrer ?", 'audit',
  "La question du premier recrutement bloque beaucoup de dirigeants.",
  "Ce qui se fait sans, ce qui l'exige vraiment."),

 # ── Automatisation et workflows ───────────────────────────────────────────
 ('n8n-vs-make-vs-zapier', "n8n, Make ou Zapier : lequel pour une PME française", 'automatisation',
  "Trois outils, trois modèles de facturation, trois pièges.",
  "Le coût réel à 12 mois selon le volume, pas le tarif affiché."),
 ('automatiser-devis-batiment', "Automatiser la production de devis sans perdre la main dessus", 'automatisation',
  "Le devis est le document le plus chronophage et le plus sensible.",
  "Ce qu'on automatise, ce qu'on garde sous contrôle humain."),
 ('automatiser-relances-clients', "Relances clients : automatiser sans passer pour un robot", 'automatisation',
  "Une relance automatique mal écrite abîme la relation.",
  "Le seuil au-delà duquel l'automatisation se voit."),
 ('tri-emails-automatique', "Trier et router ses e-mails entrants automatiquement", 'automatisation',
  "La boîte partagée est un point de perte quotidien.",
  "Routage par intention plutôt que par mot-clé."),
 ('saisie-factures-fournisseurs', "Supprimer la saisie des factures fournisseurs", 'automatisation',
  "Une saisie qui coûte plusieurs jours par mois et n'apporte rien.",
  "Extraction, contrôle, et le point où l'humain doit rester."),
 ('automatisation-comptes-rendus', "Comptes rendus de réunion : de l'enregistrement au compte rendu diffusé", 'automatisation',
  "Le compte rendu est toujours en retard, souvent jamais écrit.",
  "La chaîne complète, et la question du consentement."),
 ('workflow-recrutement-ia', "Automatiser le tri de candidatures sans discriminer", 'automatisation',
  "Le tri automatique de CV est un terrain juridiquement miné.",
  "Ce que la loi interdit, et ce qui reste possible."),
 ('quand-ne-pas-automatiser', "Quand il ne faut surtout pas automatiser", 'automatisation',
  "L'automatisation est vendue comme toujours bénéfique. Elle ne l'est pas.",
  "Quatre situations où automatiser détruit de la valeur."),
 ('automatisation-erreurs-silencieuses', "Les pannes silencieuses : le vrai risque de l'automatisation", 'automatisation',
  "Un flux qui échoue sans prévenir fait plus de dégâts qu'une panne visible.",
  "Comment rendre une automatisation bavarde quand elle échoue."),
 ('reprendre-la-main-automatisation', "Reprendre la main sur une automatisation qui dérive", 'automatisation',
  "Six mois après, personne ne sait plus ce que fait le flux.",
  "Documentation minimale et point de reprise manuelle."),

 # ── Modèles et LLM ────────────────────────────────────────────────────────
 ('choisir-modele-selon-tache', "Choisir son modèle d'IA selon la tâche, pas selon la mode", 'modeles',
  "Le meilleur modèle n'existe pas ; le meilleur pour une tâche, oui.",
  "Une grille tâche par tâche, sans classement général."),
 ('modeles-ouverts-vs-proprietaires', "Modèles ouverts ou propriétaires : le vrai arbitrage", 'modeles',
  "L'ouverture est vendue comme une garantie. De quoi, exactement ?",
  "Ce que l'ouverture change vraiment sur le coût et la maîtrise."),
 ('fenetre-contexte-pourquoi-ca-compte', "La fenêtre de contexte : pourquoi ça change tout", 'modeles',
  "Notion technique, conséquence très concrète sur ce qu'on peut faire.",
  "Ce qu'on peut traiter d'un coup selon la taille de fenêtre."),
 ('hallucinations-comment-limiter', "Les hallucinations : les comprendre pour les contenir", 'modeles',
  "Un modèle qui invente avec aplomb est plus dangereux qu'un modèle muet.",
  "Trois dispositifs qui réduisent le risque sans le supprimer."),
 ('modele-francais-souverainete', "Un modèle français change-t-il quelque chose à la souveraineté ?", 'modeles',
  "Le drapeau ne suffit pas : où sont les données, qui y accède ?",
  "Les questions à poser à un hébergeur, quelle que soit sa nationalité."),
 ('cout-reel-api-llm', "Le coût réel d'une API de modèle, au-delà du tarif affiché", 'modeles',
  "Le prix au million de tokens ne dit presque rien de la facture.",
  "Les postes cachés : contexte répété, tentatives, raisonnement."),
 ('modeles-raisonnement-quand', "Les modèles à raisonnement : quand ils valent leur coût", 'modeles',
  "Ils coûtent plus cher et sont plus lents. Pour quel gain ?",
  "Les tâches où l'écart se voit, celles où il ne se voit pas."),
 ('rag-explique-simplement', "Faire répondre l'IA sur VOS documents : le principe expliqué", 'modeles',
  "Comment un modèle peut-il connaître des documents internes ?",
  "Le principe sans jargon, et ses limites réelles."),
 ('multimodal-a-quoi-ca-sert', "Modèles multimodaux : à quoi ça sert concrètement en entreprise", 'modeles',
  "Lire une image ou un PDF change beaucoup de flux métier.",
  "Cinq usages où le multimodal supprime une saisie."),
 ('changer-de-modele-sans-tout-refaire', "Changer de modèle sans tout refaire", 'modeles',
  "S'attacher à un fournisseur est le risque le plus sous-estimé.",
  "Ce qu'il faut isoler dès le départ pour rester libre."),

 # ── Conduite du changement ────────────────────────────────────────────────
 ('equipes-refusent-ia', "Quand les équipes refusent l'IA : comprendre avant de convaincre", 'conduite',
  "Le refus est presque toujours rationnel. Lequel ?",
  "Les quatre peurs réelles, et ce qui répond à chacune."),
 ('annoncer-projet-ia-equipes', "Annoncer un projet IA à ses équipes sans déclencher la panique", 'conduite',
  "La première annonce fixe le climat de tout le projet.",
  "Ce qu'il faut dire, et ce qu'il ne faut jamais promettre."),
 ('ia-et-suppression-postes', "L'IA va-t-elle supprimer des postes chez moi ?", 'conduite',
  "La question que tout le monde pense et que personne ne pose.",
  "Une réponse honnête, chiffres à l'appui, sans langue de bois."),
 ('choisir-premier-service-pilote', "Choisir le service pilote : celui qui décide de la suite", 'conduite',
  "Un pilote mal choisi enterre le sujet pour deux ans.",
  "Les critères de choix, et le service à éviter absolument."),
 ('sponsor-projet-ia', "Sans sponsor, un projet IA meurt : pourquoi et comment l'éviter", 'conduite',
  "Le projet sans portage s'arrête au premier arbitrage budgétaire.",
  "Qui doit porter, et ce que porter veut dire concrètement."),
 ('mesurer-adoption-reelle', "Mesurer l'adoption réelle, pas les connexions", 'conduite',
  "Tout le monde s'est connecté une fois. Et après ?",
  "Trois indicateurs d'usage qui ne mentent pas."),
 ('gouvernance-ia-pme', "Une gouvernance IA proportionnée à une PME", 'conduite',
  "Les cadres de gouvernance sont écrits pour des groupes.",
  "Le strict nécessaire : trois règles, un référent, une revue."),
 ('shadow-ai-en-entreprise', "L'IA clandestine : vos équipes l'utilisent déjà", 'conduite',
  "L'usage non encadré existe avant tout projet officiel.",
  "Comment le constater sans surveiller, et quoi en faire."),
 ('former-ou-recruter', "Former ses équipes ou recruter : le calcul", 'conduite',
  "Deux stratégies, deux coûts, deux délais.",
  "Le point de bascule selon la taille et le secteur."),
 ('ia-et-management-intermediaire', "Le management intermédiaire, angle mort des projets IA", 'conduite',
  "Le blocage vient rarement du terrain ni de la direction.",
  "Pourquoi cette strate résiste, et ce qui la débloque."),

 # ── Conformité et sécurité ────────────────────────────────────────────────
 ('rgpd-ia-ce-qui-change', "RGPD et IA : ce qui change vraiment pour une PME", 'conformite',
  "Le règlement existait avant l'IA. Qu'est-ce qui est nouveau ?",
  "Les trois points où l'IA crée une obligation supplémentaire."),
 ('donnees-clients-dans-chatgpt', "Coller des données clients dans un outil d'IA : que risque-t-on ?", 'conformite',
  "Le geste est quotidien, la conséquence rarement mesurée.",
  "Ce que dit le droit, et ce que disent les conditions d'usage."),
 ('ia-act-europeen-pme', "Le règlement européen sur l'IA : ce qu'une PME doit en retenir", 'conformite',
  "Un texte long, dont l'essentiel tient en une page pour une PME.",
  "Les catégories de risque, et où tombent les usages courants."),
 ('anonymiser-avant-envoi', "Anonymiser avant d'envoyer : méthodes et limites", 'conformite',
  "L'anonymisation est présentée comme la solution. Elle est fragile.",
  "Ce qui protège vraiment, et ce qui ne fait qu'y ressembler."),
 ('modele-local-quand-necessaire', "Modèle hébergé chez soi : quand c'est vraiment nécessaire", 'conformite',
  "Le local rassure mais coûte. Quand est-ce justifié ?",
  "Trois critères de décision, et l'ordre de grandeur du coût."),
 ('journalisation-usages-ia', "Journaliser les usages IA : obligation ou précaution ?", 'conformite',
  "Savoir qui a demandé quoi, et pourquoi c'est utile.",
  "Ce qu'il faut garder, combien de temps, et à quoi ça sert."),
 ('clause-ia-contrat-client', "Faut-il une clause IA dans ses contrats clients ?", 'conformite',
  "Si l'IA intervient dans la prestation, le client doit-il le savoir ?",
  "Les cas où l'information est due, et une formulation type."),
 ('secret-professionnel-et-ia', "Secret professionnel et IA : les métiers concernés", 'conformite',
  "Avocat, expert-comptable, santé : le secret change tout.",
  "Ce qui reste possible sous secret, et à quelles conditions."),
 ('fuite-donnees-par-lia', "Comment une fuite de données arrive par l'IA", 'conformite',
  "Les scénarios réels, pas les scénarios de film.",
  "Quatre chemins de fuite constatés, et le garde-fou de chacun."),
 ('assurance-et-risque-ia', "Votre assurance couvre-t-elle une erreur causée par l'IA ?", 'conformite',
  "Question rarement posée avant l'incident.",
  "Ce qu'il faut vérifier dans son contrat, en trois points."),

 # ── Par métier ────────────────────────────────────────────────────────────
 ('ia-service-commercial', "L'IA au service commercial : trois usages qui tiennent", 'metiers',
  "Beaucoup de promesses, peu d'usages qui survivent à six mois.",
  "Ce qui reste en place, et pourquoi le reste tombe."),
 ('ia-comptabilite-pme', "Comptabilité : ce que l'IA fait bien et ce qu'elle rate", 'metiers',
  "Le chiffre exact ne tolère pas l'approximation.",
  "La frontière entre extraction et interprétation."),
 ('ia-service-client', "Service client : l'IA sans dégrader la relation", 'metiers',
  "Le chatbot mal fait coûte des clients.",
  "Le niveau où l'IA aide, celui où elle nuit."),
 ('ia-ressources-humaines', "RH : les usages IA qui ne posent pas de problème juridique", 'metiers',
  "Beaucoup d'usages RH sont encadrés ou interdits.",
  "La liste de ce qui est sûr, et pourquoi."),
 ('ia-marketing-contenu', "Marketing de contenu : produire plus sans produire du vide", 'metiers',
  "Le volume est facile, la valeur ne l'est pas.",
  "Le processus qui garde une voix reconnaissable."),
 ('ia-achats-fournisseurs', "Achats : comparer des offres avec l'IA", 'metiers',
  "Comparer dix propositions techniques prend des jours.",
  "Ce qui s'automatise dans la comparaison, ce qui ne s'automatise pas."),
 ('ia-juridique-interne', "Juridique interne : relire des contrats avec l'IA", 'metiers',
  "Gain de temps réel, risque réel aussi.",
  "L'usage qui fonctionne : repérer, pas décider."),
 ('ia-production-industrielle', "Production : au-delà de la maintenance prédictive", 'metiers',
  "Le seul cas d'usage cité est rarement le plus accessible.",
  "Trois usages plus simples et plus rentables à démarrer."),
 ('ia-logistique-transport', "Logistique : planification et gestion des aléas", 'metiers',
  "La planification théorique existe déjà. L'aléa, non.",
  "Là où l'IA apporte : la replanification, pas le plan."),
 ('ia-direction-generale', "Ce qu'un dirigeant peut faire lui-même avec l'IA", 'metiers',
  "Avant de déployer, il faut avoir pratiqué.",
  "Cinq usages personnels qui forment le jugement."),

 # ── Par secteur ───────────────────────────────────────────────────────────
 ('ia-cabinet-expertise-comptable', "IA en cabinet d'expertise comptable", 'secteurs',
  "Volume documentaire énorme, tolérance à l'erreur nulle.",
  "Les usages compatibles avec la responsabilité professionnelle."),
 ('ia-btp-entreprise-generale', "IA dans le bâtiment : les usages qui tiennent sur chantier", 'secteurs',
  "Un chantier n'est pas un bureau : réseau, mains sales, urgence.",
  "Ce qui résiste aux conditions réelles."),
 ('ia-commerce-detail', "Commerce de détail : prévision et réassort", 'secteurs',
  "Le stock immobilise la trésorerie ; la rupture perd la vente.",
  "Ce que l'IA améliore, et le volume minimal pour que ça marche."),
 ('ia-agence-communication', "Agence de communication : rester créatif quand tout le monde génère", 'secteurs',
  "Quand la production devient gratuite, la valeur se déplace.",
  "Où se déplace-t-elle exactement."),
 ('ia-cabinet-avocat', "Cabinet d'avocats : recherche et rédaction sous contrainte de secret", 'secteurs',
  "Le secret professionnel interdit la plupart des outils grand public.",
  "Les configurations acceptables, techniquement et déontologiquement."),
 ('ia-sante-liberale', "Professions de santé libérales : le cadre avant l'outil", 'secteurs',
  "Données de santé : le régime le plus strict.",
  "Ce qui est possible, et l'hébergement exigé."),
 ('ia-industrie-agroalimentaire', "Agroalimentaire : traçabilité et contrôle qualité", 'secteurs',
  "La traçabilité est déjà une obligation lourde.",
  "Comment l'IA allège la charge sans créer de risque."),
 ('ia-immobilier-agence', "Agence immobilière : de l'annonce au dossier de location", 'secteurs',
  "Beaucoup de saisie répétée, beaucoup de documents.",
  "La chaîne complète, étape par étape."),
 ('ia-formation-organisme', "Organisme de formation : concevoir plus vite sans perdre en qualité", 'secteurs',
  "La conception pédagogique est le poste le plus coûteux.",
  "Ce que l'IA fait bien en conception, et ce qu'elle rate."),
 ('ia-association-secteur-social', "Associations : faire plus avec des moyens contraints", 'secteurs',
  "Pas de budget informatique, beaucoup d'administratif.",
  "Ce qui se met en place sans budget ni compétence technique."),

 # ── Formation et compétences ──────────────────────────────────────────────
 ('former-equipes-par-ou-commencer', "Former ses équipes à l'IA : par où commencer", 'formation',
  "Former tout le monde à tout ne marche jamais.",
  "L'ordre qui fonctionne : qui, quoi, dans quel ordre."),
 ('prompt-engineering-utile-ou-mode', "Le prompt engineering : compétence durable ou effet de mode ?", 'formation',
  "Compétence très mise en avant. Restera-t-elle ?",
  "Ce qui restera, ce qui disparaîtra avec les prochains modèles."),
 ('duree-formation-ia-efficace', "Combien de temps faut-il pour former quelqu'un à l'IA ?", 'formation',
  "Une demi-journée ne suffit pas, cinq jours sont un luxe.",
  "Le format qui produit un changement mesurable."),
 ('evaluer-competences-ia', "Évaluer le niveau réel de ses équipes en IA", 'formation',
  "L'autoévaluation est systématiquement fausse, dans les deux sens.",
  "Une évaluation par la tâche, pas par le questionnaire."),
 ('entretenir-competences-ia', "Entretenir les compétences quand les outils changent tous les trois mois", 'formation',
  "La formation ponctuelle se périme vite.",
  "Le dispositif léger qui maintient le niveau."),
 ('former-dirigeant-ou-equipes', "Faut-il former le dirigeant avant les équipes ?", 'formation',
  "Un dirigeant qui ne pratique pas ne saura pas arbitrer.",
  "Pourquoi l'ordre compte plus qu'on ne croit."),
 ('referent-ia-interne', "Désigner un référent IA en interne : profil et mission", 'formation',
  "Ni informaticien, ni expert : quel profil alors ?",
  "La fiche de mission réelle, et le temps à y consacrer."),
 ('apprendre-par-la-pratique-ia', "Apprendre l'IA par la pratique : un protocole en quatre semaines", 'formation',
  "La théorie sans pratique ne produit aucun changement.",
  "Un protocole applicable sans accompagnement."),
 ('erreurs-formation-ia', "Les formations IA qui ne servent à rien, et pourquoi", 'formation',
  "Beaucoup de formations laissent zéro trace un mois après.",
  "Les quatre défauts de conception qui l'expliquent."),
 ('financer-formation-ia', "Financer une formation IA : les dispositifs réellement mobilisables", 'formation',
  "Beaucoup de dispositifs annoncés, peu accessibles à une PME.",
  "Ce qui est mobilisable en pratique, et la démarche."),

 # ── ROI et pilotage ───────────────────────────────────────────────────────
 ('calculer-roi-ia-methode', "Calculer le retour d'un projet IA : la méthode honnête", 'pilotage',
  "Les calculs de retour sur investissement sont souvent complaisants.",
  "Une méthode qui inclut les coûts qu'on oublie toujours."),
 ('combien-couter-projet-ia-pme', "Combien coûte réellement un projet IA en PME", 'pilotage',
  "Les fourchettes annoncées vont de 1 à 100.",
  "La décomposition des postes, licence comprise et cachée."),
 ('indicateurs-suivre-projet-ia', "Les indicateurs à suivre, et ceux qui trompent", 'pilotage',
  "Les indicateurs faciles à mesurer sont rarement les bons.",
  "Trois indicateurs utiles, trois indicateurs pièges."),
 ('quand-arreter-projet-ia', "Savoir arrêter un projet IA qui ne prend pas", 'pilotage',
  "Persister coûte plus cher qu'arrêter, et c'est difficile à admettre.",
  "Les signaux d'arrêt, et comment arrêter sans casser la dynamique."),
 ('budget-ia-premiere-annee', "Quel budget IA pour une première année", 'pilotage',
  "Trop peu ne produit rien, trop crée un chantier ingérable.",
  "Un ordre de grandeur selon la taille, et sa répartition."),
 ('interne-ou-prestataire', "Faire en interne ou passer par un prestataire", 'pilotage',
  "Les deux échouent pour des raisons différentes.",
  "La règle de partage : ce qui doit rester interne."),
 ('contractualiser-mission-ia', "Contractualiser une mission IA : les clauses qui comptent", 'pilotage',
  "Les livrables flous sont la première cause de litige.",
  "Cinq clauses à exiger, formulées."),
 ('mesurer-temps-gagne', "Mesurer le temps réellement gagné, pas le temps annoncé", 'pilotage',
  "Le temps gagné déclaré est presque toujours surestimé.",
  "Un protocole de mesure avant/après tenable."),
 ('effet-plateau-projets-ia', "L'effet plateau : pourquoi les gains s'arrêtent au bout de six mois", 'pilotage',
  "Les premiers gains sont faciles, les suivants non.",
  "Ce qui explique le plateau, et comment le franchir."),
 ('presenter-resultats-ia-direction', "Présenter les résultats d'un projet IA à son conseil", 'pilotage',
  "Les chiffres techniques n'intéressent personne au conseil.",
  "La structure de présentation qui obtient la suite du budget."),

 # ── Mise en œuvre technique ───────────────────────────────────────────────
 ('connecter-ia-crm', "Connecter l'IA à son CRM sans tout casser", 'technique',
  "Le CRM est le système le plus sensible à toucher.",
  "L'ordre d'intégration qui limite le risque."),
 ('ia-et-erp-existant', "Faire parler l'IA avec un ERP ancien", 'technique',
  "Beaucoup d'ERP en place n'ont pas d'interface moderne.",
  "Les trois voies possibles, avec leurs coûts."),
 ('ia-microsoft-365', "Microsoft 365 : ce que Copilot fait, ce qu'il ne fait pas", 'technique',
  "La licence est souvent achetée avant d'être comprise.",
  "Ce qui justifie la licence, et les alternatives."),
 ('preparer-ses-documents-ia', "Préparer ses documents pour que l'IA les exploite", 'technique',
  "Un PDF scanné n'est pas un document exploitable.",
  "Le travail de préparation, souvent sous-estimé."),
 ('api-ou-interface-web', "Passer par une API ou par l'interface web : quand basculer", 'technique',
  "L'interface web suffit longtemps, puis ne suffit plus.",
  "Le seuil de bascule, et ce qu'il implique."),
 ('tester-une-ia-avant-deploiement', "Tester une IA avant de la déployer : protocole", 'technique',
  "On déploie souvent sur une impression, pas sur une mesure.",
  "Un jeu de test constitué en une journée."),
 ('surveiller-qualite-en-production', "Surveiller la qualité d'une IA en production", 'technique',
  "La qualité dérive sans prévenir quand le modèle change.",
  "Le dispositif minimal de surveillance."),
 ('cout-maintenance-solution-ia', "Ce que coûte l'entretien d'une solution IA après la mise en service", 'technique',
  "Le coût de mise en service est visible, l'entretien ne l'est pas.",
  "Les postes récurrents, en ordre de grandeur."),
 ('integrer-ia-outils-metier-verticaux', "Intégrer l'IA à un logiciel métier spécialisé", 'technique',
  "Les logiciels verticaux sont fermés et peu documentés.",
  "Les points d'entrée possibles quand il n'y a pas d'API."),
 ('sauvegarde-reversibilite-ia', "Réversibilité : pouvoir revenir en arrière", 'technique',
  "Un déploiement sans marche arrière est un pari.",
  "Ce qu'il faut conserver pour pouvoir revenir."),
]

if __name__ == '__main__':
    from collections import Counter
    c = Counter(s[2] for s in SUJETS)
    print(f'  {len(SUJETS)} sujets · {len(set(s[0] for s in SUJETS))} slugs uniques')
    for p, n in c.most_common():
        print(f'   {POLES[p]:28} {n:>3}')
    doublons = [s for s, n in Counter(x[0] for x in SUJETS).items() if n > 1]
    print(f'  doublons de slug : {doublons or "aucun"}')
